### ISSUE TITLE
Recreate the old Worm cape generator utility

### ISSUE THREAD

**Issue by VariableVixen** [PrincessRTFM/WebUtil#1]
I lost the old code, but honestly it could've been done so much better anyway so it's not really much of an issue. But it turns out that some people did actually get use out of the thing, so I'm going to put together a new one; the problem is I need powers to put in it. To that end, **please post any power ideas and suggestions here**, along with any requests for features.

**Comment by Edmandias** [comment]
The last power I had was the power to copy the powers of the last parahuman I touched
Tinker who specializes in weapons.
Tinker who specializes in armor.
Tinker who specializes in augmentation
Tinker who specializes in biotech.
Tinker who specializes in sound.
Changer/Striker who can turn into any living thing they have touched in the last fifteen minutes.
Master who has absolute control over the last person physically touched.
Breaker/Shaker who forces cartoon physics in a perfectly spherical area of ten meters (~33 feet). Shaker who causes non-living material in an area around them to slowly break down, unless they actively suppress the effect.
hinker who has unlimited omniscience within a certain range.
Shaker who makes objects move slower when approaching them, and faster when going away from them.
Master/Shaker/Thinker who makes themselves more intelligent by temporarily making those around them less so.
Tinker who specializes in portals.
Shaker who decreases the speed of anything within range that they feel threatened by, to a minimum of one mile per hour.
Breaker/Shaker who creates things by drawing; the more intricate and detailed the drawing, the more complex the end result will be.
Master who controls people through voodoo dolls.
Brute/Mover who has superspeed when above a certain level of light, and super strength when below it.
Blaster/Striker who can cause objects thrown by them to explode at will; the denser the object, the bigger the explosion.

**Comment by VariableVixen** [comment]
The main effort right now is finding an at least not _awful_ way to write the randomisation engine. The main problem with _that_ is that powers can fall under multiple classifications, which means that no matter how I write the actual power entry itself, I need to "tag" it with the relevant classifications out of the twelve, and doing that even vaguely close to well is... not the easiest thing.

Notes for myself and anyone interested:
- Can't do a map of `{ CLASS: [POWER, POWER, POWER, ...] }` because then powers would have to be written into multiple places
	- Can't use an array of tags for the key because even if that weren't _begging_ for trouble, JS won't allow it
- Could do a map of `{ POWER: [CLASS, CLASS, ...] }` but that offends me on multiple levels
	- Still, I admit it would _work_
- Could do an array of `[ [POWER, CLASS, CLASS, ...] ]` or something similar (several formats come to mind) but that's no better for sorting/filtering than the above, and manages to offend me even more, so that's probably right out
	- Actually, it would allow sorting directly - arrays can be sorted, objects can't - instead of having to make a sorted list of powers out of the object keys
		- Except the "keys" are actually the powers to be displayed, they'd need to be filtered into a separate list either way, and there's not actually a point in sorting when they're going to be pulled from at random
- Could do an array of custom `Power` objects, which would also let me hide additional magic behind the scenes so it updates easily with new ideas...
	- Filtering would be easy enough, and could easily be rewritten any time I have a better idea without rewriting the whole damn engine
	- The stringification method could incorporate additional randomisation, so that small details could change easily without needing a whole new _almost_ identical entry

**Comment by VariableVixen** [comment]
Okay, MVP is implemented and the list has been populated with everything you posted here. It's not a _lot_, but given that most of them have variations, I'll upload it now. Any new ideas, please post on the newly made [dedicated thread](https://github.com/PrincessRTFM/WebUtil/issues/2). I'll see about reimplementing the old category filters too.
